on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Install depedencies
      run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
    - name: Run Tests
      run: |
            coverage run -m unittest
            coverage xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
      with:
        args: >
          -Dsonar.organization=rodo7936
          -Dsonar.projectKey=rodo7936_py4me
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=py4me/
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
